name: Deploy MCP Server

on:
  push:
    branches:
      - main
    paths:
      - 'src/titanic/mcp_server/**'
      - '/tests/mcp_server/**'
      - 'k8s/mcp_server/**'
      - '.github/workflows/deploy-mcp-server.yml'
  workflow_dispatch:

env:
  MCP_SERVER_IMAGE_NAME: quay.io/yacinekerrad/titanic/mcp-server
  MCP_SERVER_DEPLOYMENT_NAME: titanic-mcp-server
  MCP_SERVER_SECRET_NAME: mcp-oauth2-credentials

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
            echo "To implement"
          
          # TODO: Saisir la suite de cette pipeline. Devrait apparaître : 
          # Install depencies, Launch unit tests,
          # Configure docker and kubectl, Build and push Docker image
          # Create OAuth2 secret, Delete MCP Server pod to refresh secret,
          # Configure MCP manifest with OAuth2 domain, Deploy to OpenShift